### ISSUE TITLE
perform manual check: 'Validate'

### ISSUE THREAD

**Issue by SferaDev** [EyeSeeTea/metadata-synchronization#328]
To be discussed with @adrianq 

- [x]  Auto-map suggestion: Contextual action that queries remote instance for a DE/OU/COC/... that matches code/name (ilike, startsWith, token) and opens the mapping dialog with the filters applied to the ones that match => Moved to #359
- [x] View the metadata mapping that will be applied in the summary for data synchronizations (on-demand and sync rule) => @xurxodev => Move to #370
- [x] Add an option to execute the synchronization without committing changes (dry run) => @xurxodev => Move to #357

Missing tasks from https://github.com/EyeSeeTea/metadata-synchronization/issues/161
- [x] Add button to perform manual check: 'Validate'
- [x] Modify table loading spinner to include a message (d2-ui-components). It should say something like 'Checking destination org units'
