### ISSUE TITLE
Refactor mapping - aggregated

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/metadata-synchronization#382]
- [x] Create an intermediate page for mapping: aggregated, tracker and org unit.
- [x] Split mapping in three pages:
   - [x] DE (type aggregated), category option and category combos
   - [x] DE (type tracker), category option and category combos
   - [x] Org Unit
- [x] Do not make connection on init. Everything will be on-demand.

**Aggregated Mapping on-demand check**
- [x] When a DE is mapped to another DE the app will check if (1) the category options matched (automapping in origin and destiny) and, if there are option sets, if (2) they also matched (automapping in origin and destiny)
- [x] If category options do not match we highlight the row and enable the resolution dialog/wizard
- [ ] Add refresh button to reload on-demand check (moved to #389)

**Table filtering and Aggregated Mapping Wizard**
- [x] Dialog/Wizard will have a step for cat options and another step for option sets if any:
   - [x] Cat option step will show a table to perform the mapping of the cat options assigned to that DE on origin and the cat options assigned to DE on destiny.
  - [x] Option set step will show a table to perform the mapping of the options assigned to that DE on origin and the options assigned to DE on destiny.
- [x] Add "Related metadata mapping" contextual action that opens the mapping wizard.
  - [x] If there isn't a DE mapping we will show a snack bar explaining the user needs to perform the DE mapping. 
- [ ] If there are conflict left-click will also open the related metadata mapping wizard. (moved to #389)
- [ ] Filter to show only conflicting rows. (moved to #389)

**Sync logic and globals**
- [x] Update sync logic to use nested mapping
- [ ] On sync, if there is any conflict we show a snackbar telling the user to solve the conflicts (moved to #389)
- [ ] For each wizard step we should allow the user to make this mapping global instead of for a particular DE (Not for now. @adrianq to ask Nacho) (moved to #389)

**Comment by adrianq** [comment]
"metadataMapping": {
      "dataElements": {
        "tpz77FcntKx": {
          "categoryOptions": {
            "conflicts": false,
            "UPvKbcqTEY3": {
              "mappedId": "wTpH7wugXzZ",
              "name": "15+ years",
              "conflicts": false,
              "mapping": {
                "categoryOptions": {
                  "conflicts": false
                },
                "options": {
                  "conflicts": false
                }
              }
            }
          },
          "options": {
            "ZRFmR9WhhRR": {
              "mappedId": "DISABLED",
              "conflicts": true
            },
            "MDL3sm4eyqn": {
              "mappedId": "DISABLED",
              "conflicts": true
            },
            "O3kJvVAUQik": {
              "mappedId": "DISABLED",
              "conflicts": true
            }
          }
        }
      }
