### ISSUE TITLE
Refactor mapping - events

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/metadata-synchronization#389]
### Tasks

- [x] Make model of ``MappingDialog`` depend on row instead of page
- [x] Fix name shown on ``MappingDialog`` for children rows
- [x] Inject ``__mappingType__`` and ``__mappingId__`` to model transform
- [x] Store in the datastore ``uid1-uid2`` identifiers and use them in the table mapping
- [x] Adapt logic for events syncrhonization based on the new mapping
- [x] Hide/show wizard sections depending on the type
- [x] Add name and id to "Related metadata mapping`` dialog title
- [x] Prettify metadata type (with data from schemas on d2-api)

### Details

- A table with two levels of nested program and DE
- Related mapping objects are Category Combo for the program and Option Set for the DE
- Example:
Program - Category Combo
   -> DE1 - Option Set
   -> DE2
- Data Store
```
"metadataMapping": {
      "programs": {
        "tpz77FcntKx": {
          "programStageInstances": {
          "sfih1243dfs":{
                    "dataElements":{
                              "hello1234": {
                                        "optionSets": {
                                                        "mappedId": "wTpH7wugXzZ",
                                                        "name": "15+ years",
                                                        "conflicts": false,}
          },
          "categoryOptions": {
```

### Mock-ups

![image](https://user-images.githubusercontent.com/2181866/75314272-8aadba00-585f-11ea-8dca-45bd31e0a2d9.png)
![image (1)](https://user-images.githubusercontent.com/2181866/75314273-8b465080-585f-11ea-83b5-600f9f49815c.png)
![image (2)](https://user-images.githubusercontent.com/2181866/75314269-8a152380-585f-11ea-86b0-f8328a3d72cc.png)
![image (3)](https://user-images.githubusercontent.com/2181866/75314270-8aadba00-585f-11ea-91d6-a656a7f81432.png)
