### ISSUE TITLE
Update docker images with latest datastore version

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/metadata-synchronization#488]
## Tasks

The goal is to support the synchronization to different versions where
we will need to transform generated payload to specific versions needs

The user experience should not change to sync against different server versions.

We should apply consecutive transformations to package until the need last transformation
 example: if exists transformations for versions 30,31,33 and version of the server to sync is 31 then
 transformations 30 and 31 will be applied

![image](https://app.gitkraken.com/api/glo/boards/5da04a8d796a7c000f8784e0/attachments/5ea01b52f95f6f0011e8c589)

Current our needs are to transform the payload before to send it to receiver server, this payload is sent
to the server using the non-typed post method of D2 API.

The mapper concept used frequently in Clean Architecture may be a valid option together with the strategy pattern
to have a transformation by version to use in current sync classes may be sufficient.

Ideally, this mappers would transform from domain payload to versioned d2 payload,
if now we have not time to refactor all code of current syncs to Clean Architecture then now can map
from the current dynamic payload to other versions using any typescript type in mappers.

### Minimum tasks to create Sync version infrastructure

- [ ] Create a data/synchronization/mappers layer
- [ ] Create mapper to realize consecutive transformations to a package
 using generic transformations list of EventsPackage, AggregatedPackage, MetadataPackage type
- [ ] Create tests for mapper
- [ ] Create system info model in d2 API  --> Arnau
- [ ] Use mapper previously to post payload from synchronizations
- [ ] From synchronizations retrieve the target server version 

### Refactor tasks related to creating sync version infrastructure
- [ ] Move  EventsPackage, AggregatedPackage, MetadataPackage to domain layer
- [ ] Create instance domain entity and repository with only need to this task and use this repository to 
retrieve current instance data with version property

### Possible next tasks doing baby steps to Clean Architecture on future tasks

I think the strategy should be with baby steps creating domain entities and repositories of synchronization dependencies

- Create domain entity User or UserAccount, repository and use it from synchronizations
- Create domain entity Instance, repository and use it from synchronizations
- Create domain entity SyncReport, repository and use it from synchronizations
- Create domain entity syncRule, repository and use it from synchronizations
- Create domain entities for metadata
- Create repository/s for metadata and use it from metadata synchronization
- modify metadata on-demand page to get use case from context provider
- use metadataSyncUseCase from metadata on-demand page
- modify sync rule list page to get use case from context provider
- use metadataSyncUseCase from the sync rule list 

...

- Rename metadata to use cases and move under domain folder
- create contexts provider/s (composition root/s) to retrieve use case/s (with injected repositories)
