### ISSUE TITLE
Create infrastructure to realize package transformations by d2 version previously to upload

### ISSUE THREAD

**Issue by xurxodev** [EyeSeeTea/metadata-synchronization#507]
The goal is to support the synchronization to different versions where
we will need to transform payload generated to specific versions needs

The user experience should not change to sync against different server versions.

Current our needs are to transform the payload before to upload it to receiver server, this payload is sent
to the server using the non-typed post method of D2 API.

The mapper concept used frequently in Clean Architecture to realize transformation between layers may be a valid option together with the strategy pattern to have n transformations by version and package type.

Ideally, this mappers would transform from domain payload to versioned d2 payload,
if now we have not time to refactor all code of current syncs to Clean Architecture then now can map
from the current dynamic payload to other versions using any typescript type in mappers.

![image](https://app.gitkraken.com/api/glo/boards/5da04a8d796a7c000f8784e0/attachments/5ea0207ce93c0a00119174bc)

## Tasks:

- [x] Create system info model in d2 API to retrieve the version of server -> Arnau
- [x] Create generic mapper and transformations infrastructure to use in events, metadata and aggregated syncs
- [x] Create tests for mapper
- [x] From events, metadata and aggregated syncs synchronizations retrieve the receiver version using instance
- [x] Use version mapper to map payload previously to post it from From events, metadata and aggregated syncs and deleted objects.

## Refactor tasks to Clean Architecture:

- [x] Move MetadataPackage, EventsPackage, AggregatedPackage types to the domain layer
- [x] Create instance entity and repository with only need features to this feature
- [x] Create MetadataRepository and move invocation to the mapper and the d2api invocation to post in this repository from metadata sync
- [x] From deleted sync to invoke to MetadataRepository to make version mapping and post.

## Fixed bug:
 - [x] Synchronize button always disabled in delete objects on-demand sync  dialog

## Pending refactors
- [ ] Create get method in the metadata repository and use it from synchronizations.
- [ ] Create EventsRepository and move invocation to the mapper and the d2api invocation to post in this repository.
- [ ] Create AggregatedRepository and move invocation to the mapper and the d2api invocation to post in this repository.
- [ ] Propose a solution to composition root to inject entity repository in synchronizations. I have insert todo comments in code dependent on this refactor with //TODO: composition root:

## Pending refactors related with composition root creation
- [ ] when we have composition root I think may have sense that repositories dependency should be the current instance entity instead of d2Api because so all necessary instance data (url, usr, pwd, version) for current server is loaded once to start the app. For the moment I have not made this change because we should realize a request to the current server for every metadata sync execution where this class is created to retrieve the current version.
- [ ] In instance repository, the encryption key to decrypt password should be injected by constructor when we have composition root. Currently, the unique solution is to have a static field in instance repository as in the old instance model and to assign the value from app.jsx that It's where the encryption key is loaded using app config currently.
- [ ] on synchronizations (future use cases), we repositories should be injected by constructor when we have composition root. Currently are created from inside of synchronizations.

## Other Possible tasks doing baby steps to Clean Architecture on this or future tasks

I think the strategy should be with baby steps creating domain entities and repositories of synchronization dependencies

- Create domain entity User or UserAccount, repository and use it from synchronizations
- Create domain entity SyncReport, repository and use it from synchronizations
- Create domain entity syncRule, repository and use it from synchronizations
- modify metadata on-demand page to get use case from context provider
- use metadataSyncUseCase from metadata on-demand page
- modify sync rule list page to get use case from context provider
- use metadataSyncUseCase from metadata on-demand page

...

- Rename metadata to use cases and move under domain folder
- create contexts provider/s (composition root/s) to retrieve use case/s (with injected repositories)
