### ISSUE TITLE
Infrastructure to sync metadata from different dhis2 versions to different dhis2 versions

### ISSUE THREAD

**Issue by xurxodev** [EyeSeeTea/metadata-synchronization#513]
# Introduction
The goal of this issue is that the app must be able to sync metadata from different dhis2 versions to different dhis2 versions.

**important**: For the future, we should transform data from dhis2 to the domain using use cases and repositories from pages to create sync rule, on-demand sync etc..

## Tasks

- [x] Create necessary entities in domain layer copying necessary types from d2-API version 30
- [x] Create getMetadataByIds method in the metadata repository, returns metadata entities according to ids filter. Realize mapping from d2 to domain
- [x] Create getMetadataByType method in the metadata repository, returns metadata entities by type. Realize mapping from d2 to the domain. This method is not used for the moment, I's need improvements, add new parameters as page, order ...  It's created as template and we should use it to retrieve either metadata from dhis2
- [x] Create getMetadataFieldsByIds method in the metadata repository, returns raw specific fields of metadata dhis2 models according to ids filter. This method does not realize transformations from dhis2 to the domain because does not return domain entity but raw fields from dhis2. It's useful for example to retrieve ids fields with metadata package keys.
- [x] create typed MetadataPackage in domain to `Record<string, MetadataEntity[]>`
- [x] create D2MetadataPackage in data layer
- [x] Create infrastructure in get method to apply transformations get method in the metadata repository  
- [x] Create tests to map from dhsi2 to domain
- [x] Refactor metadata sync to use get
- [x] create remove method in metadata sync repository and use it from DeletedMetadataUseCase
- [x] Rename metadata use cases to sync metadata (metadata, deleted) and move to the domain
- [x] Advance to uncouple metadata sync use cases
