### ISSUE TITLE
Infrastructure to sync events from different dhis2 versions to different dhis2 versions

### ISSUE THREAD

**Issue by xurxodev** [EyeSeeTea/metadata-synchronization#515]
# Introduction
The goal of this issue is that the app must be able to sync aggregated from different dhis2 versions to different dhis2 versions.

**important**: For the future, we should transform data from dhis2 to the domain using use cases and repositories from pages to create sync rule, on-demand sync etc..

## Tasks
- [x] Rename events use case to sync and move to the domain
- [x] Create necessary entities in domain layer copying necessary schemas from d2-API version 30
- [x] Create event and necessary repositories (AnalyticsData?) With get and save 
- [x] move Mapper invocación from current sync to transform between domain and dhis2 version as to repositories
- [x] Create infrastructure in get method to apply transformations get method in the  repositories
- [x] Refactor events sync to use repositories 

**use getMetadataByType in metadata repository to retrieve metadata**
