### ISSUE TITLE
Metadata Mapping

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/metadata-synchronization#566]
## Description

- Mapping metadata against users metadata: 
Allow users to map the metadata from the reference instance or repo to their own. Upon import, the metadata should suffer the corresponding transformation based on the mapping  with a view to import “metadata adapted to the existing metadata in user’s  instance”. 
   - Indicators (transforming numerator and denominator): if the user wants to import indicators and he/she already has data elements that correspond to the indicator’s numerator and denominator, the user should be able to map the indicator to his/her metadata and avoid importing the num/denom data elements. 
   - Category options and group set (for transforming dashboards): Make dashboards point to category option group sets so that when the users map the reference category options grousets with theirs, the dashboards are built based on the category options groupsets.

## Tasks

- [x] Add ``mapPayload`` logic iterating through objects and its references (with collections support)
- [x] Extract models from properties with schemas
- [x] Rewrite ids with ``mapping``
- [x] Treat special scenario for indicator formulas (what about predictors?)
- [ ] Verify ``dashboards`` scenario works out of the box
- [x] Clean-up ``mapValues`` calls and simplify in multiple function calls

Future:

- [ ] Move logic to ``metadataRepository`` (it's now with the rest of logic code in utils with direct usage of ``d2-api``)
