### ISSUE TITLE
Modify import package action to use mapping

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/metadata-synchronization#667]
### Tasks

- [x] Create entity that represents a JSON data source (similar to instance entity)
- [x] Modify ``MetadataTable``
  - [x] Allow JSON as data source instead of an instance
  - [x] Modify ``metadata.list`` and ``metadata.listAll`` use cases
  - [x] Decide which filters we want to keep and move ``getFilterData`` to a use case
  - [x] Treat ``isAppConfigurator(api)`` usage
  - [x] Ignore ``OrgUnitTree`` filter when working with a JSON backend
  - [x] Ignore ``Custodians`` when working with a JSON backend
- [x] Add mapping to existing integration tests
- [x] Create entity that represents a Mapping storage and persist to data store
- [x] Update ``store`` entity to include module mapping references
- [x] Modify ``MappingTable``
  - [x] Create use case to load mapping
  - [x] Create use case to set mapping
  - [x] Create use case to auto map
  - [x] Extract logic that requires an ``api`` object
  - [x] Remove direct calls to composition root from component and move it to page

### DataStore

```
stores: [],
stores-id: {
	"module1": {
	   "mapping": id1
	 },
	"module1": {
	   "mapping": id2
	 },

},
mappings: ["id1", "id2"],
mappings-id1 : {}
```
