### ISSUE TITLE
Settings (B9)

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/metadata-synchronization#725]
Tasks:

- [x] Refactor Sync Report into clean architecture
- [x] Refactor Sync Rule into clean architecture
- [x] Add settings wheel to home page (This button will be only visible for super users)
- [x] Add ``ConfigRepository`` to detect which storage client is needed (dataStore or constant)
- [x] Refactor all hard coded usages of ``DataStoreClient`` to use the new ``ConfigRepository``
- [x] Add settings page to select between dataStore and constant storage
- [x] Add a way to change the current storage

Future:

- [ ] Refactor migrations into clean architecture (created #752)
- [ ] Select advance options available and their default values for the user (in the sync wizard) and values by default. (created #753)
- [ ] Update or remove deleted objects page (it still uses direct listing calls) => #502
- [ ] Migrate permissions into ``ConfigRepository`` (created #754)
